### PR TITLE
Implementation of transportState filter

### LINKED ISSUE #83: Add Filtering by transportState in admin list
Add Filter to show entries by transportState, primarily relevant to search for all with transportState = failed.

Desired in/as of version 2.

### PR DESCRIPTION
**Pull request by flkasper**
Resolves #83

### CODE REVIEW

**Comment by tinect** [comment]
Hey @flkasper 
thank you for the PR. When using the new filter, I miss the relevant info in the grid. What do you think of adding the transportState also in column - not just showing the red icon on createAt column?

**Comment by flkasper** [comment]
@tinect Column added.
I have also moved the failed icon to the new column, as they belong together.

**Comment by tinect** [comment]
Great, thank you! I've added a few adjustments. Would you please check the PR on your fork? https://github.com/flkasper/FroshPlatformMailArchive/pull/1

**Comment by flkasper** [comment]
@tinect I had also considered including your adjustments, but then left them out because they are only indirectly related to the new feature and would usually be done in a second PR.

**Comment by tinect** [comment]
> @tinect image
> 
> you can push into prs FYI 😂

@shyim For unknown reasons I had no permissions to do so :-(

**Comment by tinect** [comment]
@flkasper thank you. I will do a few testings, create an release vor v2 and migrate it to v3.

thank you very much!

**Pull request merged**
